parameters:
    openweather.api_key: '%env(OPENWEATHER_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ImageUploadService:
        arguments:
            $targetDirectory: '%kernel.project_dir%/public/uploads/products'

    App\Service\GeminiAIService:
        arguments:
            $apiKey: '%env(OPENROUTER_API_KEY)%'

    App\Service\ProfileImageUploader:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\ImageAnalysisService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'

    App\Service\SmsService:
        arguments:
            $accountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $authToken: '%env(TWILIO_AUTH_TOKEN)%'
            $fromNumber: '%env(TWILIO_FROM_NUMBER)%'
            $enabled: '%env(bool:TWILIO_ENABLED)%'

    App\Service\OpenFoodFactsService:
        autowire: true

    App\Service\InvoiceService:
        arguments:
            $invoiceDir: '%kernel.project_dir%/var/invoices'

    App\Service\StripeService:
        arguments:
            $secretKey: '%env(STRIPE_SECRET_KEY)%'
            $publicKey: '%env(STRIPE_PUBLIC_KEY)%'

    App\CultureParcelle\Service\WeatherService:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'

    App\Command\CheckStockAlertCommand:
        tags:
            - { name: console.command }

when@test:
    services:
        _defaults:
            public: true
